Dear {customer_name},

<p>Thank you for contacting us. We have generated a Ticket (#TicketID {ticket_id}) for your Query.</p>

<p>Your Query:
{customer_query}</p>

<p>Reply:
{reply}</p> 

<p>You may check your ticket status from <a href="{ticket_link}">here</a></p>

<p>Ticket Link : {ticket_link} </p>

<p>You Can Login Into Your Account Using Following Credentials :</p>
User Name : {user_name}<br />
Password : {password}<br />

 Thanks,<br>
 iTCSLive Team