<h3>[iTCSLive] Invoice #{invoice_id}</h3>
<br>
<pre>{invoice_from}</pre>

<p>INVOICE #{invoice_id}</p>

<p>CLIENT:</p>
<pre>{invoice_client}</pre>

<p></p>
{product_details}
 <p></p>  
<p>Total (including taxes if applicable) :</p>
{total_price}

<p>To VIEW OR PRINT your invoice :</p>
<p>{invoice_link}</p>


<p>To PAY online or to view your ACCOUNT HISTORY AND BALANCE:</p>
<p>{view_pay_link}</p>


Invoice is payable now. Please make your payment quickly. If we have the
authorization and informations needed to withdraw the amount from your credit
card automaticly, we will proceed 2 or 3 days before your account's renewal date.
If your payment informations changed, please let us know.
<br />
For any question about this invoice, please contact billing at
billing@itcslive.com or call us using the phone number shown on our web sites.

<p>Thank you for your business!</p>

iTCSLive's billing team<br />
billing@itcslive.com