<p>Dear {CustomerName},</p>
<p>Thank you very much for showing interest in iTCSLive for your online business. We believe in maintaining long term customer relationships. Hence, as much as we value you, your feedback is also equally important to us. Please feel free to reach us with your queries and feedback and we will get back to you shortly.</p>
<p>For any Enquires Call Us Now</p>
<p>9836892283 / 9051158812 / 033-68888449</p>
<p>For any other query or feedback reach us at </p>
<p>info@itcslive.com / kolkata@itcslive.com</p>