<h2>A new Ticket Added for you @ itcslive by {teleexecutive_name}</h2>

Dear Sir,

  <p>As per telephonic conversation with {teleexecutive_name}. We have added your query in to our system.</p>

<p><b>Your Query:</b>
{customer_query}</p>

<p>You may check your ticket status from <a href="{ticket_link}">here</a></p>

<p>Ticket Link : {ticket_link} </p>

<p>You Can Login Into Your Account Using Following Credentials:</p>
User Name:{user_name}<br>
Password:{password}<br>

 Thanks,<br>
 iTCSLive Team